apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 2
  selector:
    app: mynginx
  template:
    metadata:
      name: mypod2
      labels:
        app: mynginx
    spec:
      containers:
        - name: mycontainer2
          image: nginx
          ports:
            - containerPort: 80
