apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavaappcontainer
          image: nginx
          ports:
            - containerPort: 80
