apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
     app: myjavaapp
     version: 2.6.1
spec:
  selector: 
    app: myjavaapp
    version: 2.6.1
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
   
